[package]
name = "advent"
version = "0.1.0"
edition = "2021"

[dev-dependencies]
criterion = { version = "0.4", features = ["html_reports"] }

[[bench]]
name = "advent"
harness = false

[dependencies]
hashbrown = "0.14.3"
ureq = "2.9.1"
